### PR TITLE
Another attempt at CentOS header fixes

### PR DESCRIPTION
**Pull request by bstopp**
This is another attempt to try to fix the CentOS kernel headers for when CentOS is released, but the new vagrant box isn't available. Or just if you want to keep using a previous version of CentOS.

This is based off the work done in #231 ; with some more specific checks.

Note: This _will_ update the `centos-release` package.
  - This is necessary to get all of the vault repos. If you are running the _current_ box, and a new release of CentOS hits, you will no longer have access to your specific packages needed to build the Guest Additions.

I tested this and it works, box 1809.1 is the latest one but 1810 is out.

Much thanks to `TrevorH` on the centos IRC channel for helping me find the info I needed to put this together.

As of this PR, this is the list of files updated when patching the `centos-release` package:

```/etc/centos-release
/etc/centos-release-upstream
/etc/issue
/etc/issue.net
/etc/os-release
/etc/pki/rpm-gpg
/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Debug-7
/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Testing-7
/etc/redhat-release
/etc/rpm/macros.dist
/etc/system-release
/etc/system-release-cpe
/etc/yum.repos.d/CentOS-Base.repo
/etc/yum.repos.d/CentOS-CR.repo
/etc/yum.repos.d/CentOS-Debuginfo.repo
/etc/yum.repos.d/CentOS-Media.repo
/etc/yum.repos.d/CentOS-Sources.repo
/etc/yum.repos.d/CentOS-Vault.repo
/etc/yum.repos.d/CentOS-fasttrack.repo
/etc/yum/vars/infra
/usr/lib/systemd/system-preset/85-display-manager.preset
/usr/lib/systemd/system-preset/90-default.preset
/usr/share/centos-release/EULA
/usr/share/doc/centos-release/Contributors
/usr/share/doc/centos-release/GPL
/usr/share/doc/redhat-release
/usr/share/redhat-release
```

### CODE REVIEW

**Comment by fnordfish** [comment]
Great work! And thanks again for making the effort.
Do I understand this correctly, that there won't be any Kernel updates, it will most likely just install the correct kernel-header?

**Comment by bstopp** [comment]
That is correct; it is only the metadata about the CentOS release; which are only specific files; not libraries. I'll update the description with those files for you.

**Comment by fnordfish** [comment]
very cool. I'll just merge it along with some other stuff and release a 0.17.0beta

**Comment by fnordfish** [comment]
released v0.17.0.beta2 (including the fix in #315)

**Comment by jaredanderson1** [comment]
> released v0.17.0.beta2 (including the fix in #315)

Sounds great, would I be able to try this out? I attempted to install with command below, but didn't work, not sure it beta versions are available to public or how these things work? thanks

vagrant plugin install vagrant-vbguest-centos --plugin-version=0.17.0.beta2

**Comment by fnordfish** [comment]
You got the wrong plugin there. Try:
vagrant plugin install vagrant-vbguest --plugin-version=0.17.0.beta2

**Pull request merged**
