### PR TITLE
(#382) Fix bug that prevents EL8 from working

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
I used the steps to reproduce from @AlexBaranowski and it works with this patch.

**Comment by ghoneycutt** [comment]
Fixes #382

**Comment by ghoneycutt** [comment]
Tested with centos/6 and centos/7 and they work fine with this.

**Comment by konstruktoid** [comment]
Ref: https://github.com/dotless-de/vagrant-vbguest/issues/367

**Comment by konstruktoid** [comment]
```
$ vboxmanage --version
6.1.12r139181
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.6
BuildVersion:   19G2021
$ vagrant --version 
Vagrant 2.2.10
$ vagrant box list | grep centos
centos/7             (virtualbox, 2004.01)
centos/8             (virtualbox, 1905.1)
```

**Comment by ghoneycutt** [comment]
Thanks @konstruktoid , I spoke with @fnordfish and he's on vacation and will check this out when he returns.

**Comment by fnordfish** [comment]
released in 0.25.0

**Pull request merged**
