### PR TITLE
added suse.rb to installers fix #219 #216

### LINKED ISSUE #219: Change to install pattern with zypper breaks SLES
Hey,
the recent change by @vpereira to install dependencies on opensuse with patterns instead of with packages breaks support for SLES.

https://github.com/dotless-de/vagrant-vbguest/commit/7bf3b7dd0596a3119e18055dae29973f0cb2e0d6

Testing confirms that after reverting the change, everything works as intended.

Tested on: SLES 12 / 11.4

### PR DESCRIPTION
**Pull request by vpereira**
Together with @glookie1 fixed issue with detecting suse and opensuse

### CODE REVIEW

**Comment by glookie1** [comment]
I just realized without my custom build package kernel-devel this fix is insufficient for SLES 11.
SLES 11 doesn't have a "kernel-devel" package, instead it is named "kernel-default-devel".

My package (attached) is just requiring kernel-default-devel.

[kernel-devel-1.0-1.x86_64.zip](https://github.com/dotless-de/vagrant-vbguest/files/327038/kernel-devel-1.0-1.x86_64.zip)

There are some questions that come to mind that need a decision:
- Is it possible to add an additional test call to the install block? Or would it be better to duplicate the suse.rb and add an additional check if OS is SLES 11? (like: `grep -q VERSION_ID=\\\"11 /etc/os-release`)
- How far back should SLES be supported? SLES 11 is already near EOL, so I personally wouldn't go back too far.

In the longer term I think it would be better to add proper support for SLES 11. But I can only solve this by duplicating suse.rb and adding the aforementioned test check.

**Comment by fnordfish** [comment]
@glensc I'd try to grep the version number in the installer and switch the package name in ruby. (see my comment: https://github.com/dotless-de/vagrant-vbguest/issues/219#issuecomment-227387699). This way you could make a weak assumption like that: `kernel_pkg = suse_version <= 11 ? "kernel-default-devel" : "kernel-devel"`

**Comment by fnordfish** [comment]
One more thing: Maybe we could use/borrow the env-parser from [bkeepers/dotenv](https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/parser.rb) for reading in the `/etc/os-release` file?

**Comment by glensc** [comment]
@fnordfish: @glookie1 not @glensc i guess :D

**Comment by fnordfish** [comment]
Oh. Right. Sorry.

**Comment by vpereira** [comment]
ok @fnordfish will take a look on that. However I would keep opensuse.rb and suse.rb since they are different things... on suse.rb I can add this logic.

**Comment by glookie1** [comment]
I hacked something together.
I couldn't get the parser to work yet, so I still have a rather hackish aproach to get the needed values.

https://github.com/glookie1/vagrant-vbguest/blob/master/lib/vagrant-vbguest/installers/suse.rb

What is yet missing:
* switch depending on pre12 or default dependencies to install
* get the parser from bkeepers/dotenv to work
* get parse_release to work with install function

Can anyone give me a hint on how to implement the switch in the install function?

**Comment by vpereira** [comment]
@fnordfish  and @glookie1  could you please take a look? You had some typos in your code @glookie1, so I just implemented it myself, using your idea as example. thanks!

**Comment by glookie1** [comment]
In line 24, you ommited an equal sign and you need to double escape the "
`communicate_to(vm).test "grep -q ID=\\\"sles\\\" /etc/os-release"`
In line 28 your return value is "12" instead of 12, so you need to add a trim
`communicate_to(vm).sudo("cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=' | tr -d '\"'", :error_check => false) do |t,d|`
Afterwards it just fails:
```
.../gems/vagrant-vbguest-0.12.0/lib/vagrant-vbguest/installers/suse.rb:13:in `install': undefined local variable or method `sles_version' for #<VagrantVbguest::Installers::Suse:0x321eef8> (NameError)
        from .../gems/vagrant-vbguest-0.12.0/lib/vagrant-vbguest/installer.rb:63:in `install'
        from .../gems/vagrant-vbguest-0.12.0/lib/vagrant-vbguest/machine.rb:94:in `block (2 levels) in guest_additions_state'
...
```

**Comment by vpereira** [comment]
hi @glookie1  thank you for your feedback. Under a 45 degrees summer in Bilbao, I was able to come up with a fix. 

Related with string escaping, AFAIK, I'm escaping already the string with \"foo\".  I think \\\"foo\\\" is just a different approach to escape strings. 

Related with the "12", needing a "trim" I'm not sure since I'm outputing the as d.to_f (it means, i'm converting it to float, it means, 12.0)

please try it and tell me what do you think!

@fnordfish  any advice?

**Comment by fnordfish** [comment]
Thanks for all your work!
I've merged this PR plus some refactoring on how to deal with the os-release file. (see b5647adbff987a01cdbd95c27699a42a65fe0637)

**Comment by vpereira** [comment]
great, thank you for this awesome piece of software and hard work!

**Pull request merged**
