### PR TITLE
Compatibility with CentOS 8

### LINKED ISSUE #367: CentOS 8 - installing Guest additions fails
Plugin version: `vagrant-vbguest (0.23.0, global)`
Vagrant version: `Installed Version: 2.2.7`
VirtualBox version: `6.1.2r135662`

VagrantFile
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.network "private_network", type: "dhcp"
  config.ssh.forward_agent = "false"
  config.ssh.keys_only = "true"
end
```

Output:
```mhemani-m1:personal mhemani$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'centos/8' version '1905.1' is up to date...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
[default] No Virtualbox Guest Additions installation found.
Last metadata expiration check: 0:00:01 ago on Fri 31 Jan 2020 03:07:39 AM UTC.
Package centos-release-8.0-0.1905.0.9.el8.x86_64 is already installed.
Dependencies resolved.
================================================================================
 Package               Arch         Version                  Repository    Size
================================================================================
Upgrading:
 centos-release        x86_64       8.1-1.1911.0.8.el8       BaseOS        21 k
Installing dependencies:
 centos-gpg-keys       noarch       8.1-1.1911.0.8.el8       BaseOS        11 k
 centos-repos          x86_64       8.1-1.1911.0.8.el8       BaseOS        12 k

Transaction Summary
================================================================================
Install  2 Packages
Upgrade  1 Package

Total download size: 44 k
Downloading Packages:
(1/3): centos-gpg-keys-8.1-1.1911.0.8.el8.noarc 9.2 kB/s |  11 kB     00:01    
(2/3): centos-repos-8.1-1.1911.0.8.el8.x86_64.r 9.9 kB/s |  12 kB     00:01    
(3/3): centos-release-8.1-1.1911.0.8.el8.x86_64  16 kB/s |  21 kB     00:01    
--------------------------------------------------------------------------------
Total                                            17 kB/s |  44 kB     00:02     
warning: /var/cache/dnf/BaseOS-31c79d9833c65cf7/packages/centos-gpg-keys-8.1-1.1911.0.8.el8.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
CentOS-8 - Base                                 791 kB/s | 1.6 kB     00:00    
Importing GPG key 0x8483C65D:
 Userid     : "CentOS (CentOS Official Signing Key) <security@centos.org>"
 Fingerprint: 99DB 70FA E1D7 CE22 7FB6 4882 05B5 55B3 8483 C65D
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: centos-gpg-keys-8.1-1.1911.0.8.el8.noarch              1/1 
  Installing       : centos-gpg-keys-8.1-1.1911.0.8.el8.noarch              1/4 
  Installing       : centos-repos-8.1-1.1911.0.8.el8.x86_64                 2/4 
  Upgrading        : centos-release-8.1-1.1911.0.8.el8.x86_64               3/4 
  Cleanup          : centos-release-8.0-0.1905.0.9.el8.x86_64               4/4 
  Running scriptlet: centos-release-8.0-0.1905.0.9.el8.x86_64               4/4 
  Verifying        : centos-gpg-keys-8.1-1.1911.0.8.el8.noarch              1/4 
  Verifying        : centos-repos-8.1-1.1911.0.8.el8.x86_64                 2/4 
  Verifying        : centos-release-8.1-1.1911.0.8.el8.x86_64               3/4 
  Verifying        : centos-release-8.0-0.1905.0.9.el8.x86_64               4/4 

Upgraded:
  centos-release-8.1-1.1911.0.8.el8.x86_64                                      

Installed:
  centos-gpg-keys-8.1-1.1911.0.8.el8.noarch                                     
  centos-repos-8.1-1.1911.0.8.el8.x86_64                                        

Complete!
Error: Unknown repo: 'C*-base'
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` --enablerepo=C*-base --enablerepo=C*-updates

Stdout from the command:



Stderr from the command:

Error: Unknown repo: 'C*-base'
```

Also since this is CentOS 8, isn't the preferred OS package manager suppose to be `dnf`?

### PR DESCRIPTION
**Pull request by pedrofurtado**
Closes #367. Based on comment of @choonge 👍 ( https://github.com/dotless-de/vagrant-vbguest/issues/367#issuecomment-602494723 )

@fnordfish 🥇

### CODE REVIEW

**Comment by fnordfish** [comment]
@pedrofurtado Thank you very much for your work. There's a very long-standing discussion where I don't like `Installers` to upgrade kernels. I realize that with CentOS, that's especially annoying. But I still stand to this descension. However, since with CentOS there seems no other way, I'm starting give up a bit.
Here's my compromise. Let's make that "upgrade kernel" an opt-in flag on the Installer:
```ruby
VagrantVbguest::Installers::CentOS.allow_kernel_upgrade = true 

# or as a new machine specific option:

Vagrant.configure("2") do |config|
  vagrant_config.vm.define name do |config|
    config.box = "centos/8"
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
  end
end
```

Another thing is rebooting via `shutdown -r now`, this way Vagrant has no chance to redo it's setup stuff (network configs and what not). Have you tried if you can trigger a reboot like this:

```ruby
module VagrantVbguest
  module Installers
    class CentOS < RedHat
      def reboot_after_install?; true end
    end
  end
end
```

**Comment by pedrofurtado** [comment]
@fnordfish  Thanks for feedback! 🍻 

Really cool that already exists a method called reboot_after_install, I did'nt realize 😆 
I will make this change (and test here) related to `reboot_after_install` instead of use of direct command `shutdown -r now`.

But a doubt: Did you plan put this flag `allow_kernel_upgrade` in what file in the plugin? I will read the source code again, to make it more familiar to me. But feel free to change the code of this PR, so lets code together 🤝  👍

**Comment by pedrofurtado** [comment]
@fnordfish Bad news: it is necessary the direct command `shutdown -r now`. If i remove it, and override the method `reboot_after_install?` with true, it gives me following error log:

```bash
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /mnt: WARNING: device write-protected, mounted read-only.
Installing Virtualbox Guest Additions 6.1.6 - guest version is unknown
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.1.6 Guest Additions for Linux........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Kernel headers not found for target kernel
4.18.0-147.3.1.el8_1.x86_64. Please install them and execute
  /sbin/rcvboxadd setup
modprobe vboxguest failed
The log file /var/log/vboxadd-setup.log may contain further information.
An error occurred during installation of VirtualBox Guest Additions 6.1.6. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start vboxadd.service
Job for vboxadd.service failed because the control process exited with error code.
See "systemctl status vboxadd.service" and "journalctl -xe" for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt
Restarting VM to apply changes...
==> default: Attempting graceful shutdown of VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/pfelipe/Desktop/repos/boa-vontade-play
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

**Comment by pedrofurtado** [comment]
@fnordfish But the PR, with the current code, works well 🏗️

**Comment by konstruktoid** [comment]
Using this PR, `vagrant up` et al works again with CentOS 8.

```
$ vboxmanage --version
6.1.6r137129
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.15.4
BuildVersion:   19E287
$ vagrant --version 
Vagrant 2.2.7
$ vagrant box list centos
centos/8 (virtualbox, 1905.1)
```

**Comment by fnordfish** [comment]
@pedrofurtado So, I've build on your work and came up with this: https://github.com/dotless-de/vagrant-vbguest/compare/pedrofurtado-patch-1

There's is now an opt-in switch `config.vbguest.installer_options = { allow_kernel_upgrade: true }` for CentOS only. This allows older CentOS boxes to use the same thing.
I also changed the place where the class decides if to do an kernel upgrade or "cross fingers and install dependencies" - I hope that doesn't break anything. It' looking good for me, but please double check.

I've realized why `reboot_after_install?` didn't work - the box needs an reboot right away after installing the new kernel. And there's no other way to do that right now.

**Comment by pedrofurtado** [comment]
@fnordfish Thank you so much for your help and code! I will test tomorrow your code, to confirm if everything works well. But, in the case of PR, the code should be like that below (for example), right?

```ruby
Vagrant.configure('2') do |config|
  config.vagrant.plugins = ['vagrant-vbguest']
  config.vbguest.auto_update = true
  config.vbguest.installer_options = { allow_kernel_upgrade: true, reboot_timeout: 5000 }
  config.vm.box = 'centos/8'
  
  # I think this line turn optional, with the new code, right? But in tests i can keep it.
  config.vm.box_url = 'https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.1.1911-20200113.3.x86_64.vagrant-virtualbox.box'
end
```

**Comment by pedrofurtado** [comment]
@pedrofurtado I will update the PR after the tests 🎉  and thanks again for fast feedback and help @fnordfish  🤝  !

**Comment by pedrofurtado** [comment]
> @pedrofurtado So, I've build on your work and came up with this: https://github.com/dotless-de/vagrant-vbguest/compare/pedrofurtado-patch-1
> 
> There's is now an opt-in switch `config.vbguest.installer_options = { allow_kernel_upgrade: true }` for CentOS only. This allows older CentOS boxes to use the same thing.
> I also changed the place where the class decides if to do an kernel upgrade or "cross fingers and install dependencies" - I hope that doesn't break anything. It' looking good for me, but please double check.
> 
> I've realized why `reboot_after_install?` didn't work - the box needs an reboot right away after installing the new kernel. And there's no other way to do that right now.

I think that is not complete yet. But we are almost there 🤝 
I dont know why, the allow_kernel_upgrade is always false, even I define it as true in Vagrantfile. I tried your code but is didn't work.

Here is the code that I tested:

```ruby
# https://github.com/dotless-de/vagrant-vbguest/issues/367
# https://github.com/dotless-de/vagrant-vbguest/pull/373
if defined?(VagrantVbguest)
  # arquivo 1
  module VagrantVbguest

    class Config < Vagrant.plugin("2", :config)

      module Attributes
        attr_accessor :auto_update, :auto_reboot, :no_install, :no_remote,
                      :installer, :installer_arguments, :installer_options,
                      :allow_downgrade,
                      :iso_path, :iso_upload_path, :iso_mount_point, :yes
      end

      class << self
        include Attributes

        def auto_update; @auto_update.nil? ? true  : @auto_update end
        def auto_reboot; @auto_reboot.nil? ? true  : @auto_reboot end
        def no_install;  @no_install.nil?  ? false : @no_install  end
        def no_remote;   @no_remote.nil?   ? false : @no_remote   end
        def installer_arguments; @installer_arguments.nil? ? '--nox11' : @installer_arguments end
        def yes; @yes.nil? ? true : @yes end

        def iso_path
          return nil if !@iso_path || @iso_path == :auto
          @iso_path
        end

        def allow_downgrade; @allow_downgrade.nil? ? false : @allow_downgrade end
      end

      include Attributes

      def auto_update; @auto_update.nil? ? self.class.auto_update : @auto_update end
      def auto_reboot; @auto_reboot.nil? ? self.class.auto_reboot : @auto_reboot end
      def no_install;  @no_install.nil?  ? self.class.no_install  : @no_install  end
      def no_remote;   @no_remote.nil?   ? self.class.no_remote   : @no_remote   end
      def installer_arguments; @installer_arguments.nil? ? self.class.installer_arguments : @installer_arguments end
      def yes; @yes.nil? ? self.class.yes : @yes end

      def iso_path
        return self.class.iso_path if !@iso_path || @iso_path == :auto
        @iso_path
      end

      def allow_downgrade; @allow_downgrade.nil? ? self.class.allow_downgrade : @allow_downgrade end

      # explicit hash, to get symbols in hash keys
      def to_hash
        {
          :installer => installer,
          :installer_arguments => installer_arguments,
          :installer_options => installer_options,
          :iso_path => iso_path,
          :iso_upload_path => iso_upload_path,
          :iso_mount_point => iso_mount_point,
          :auto_update => auto_update,
          :auto_reboot => auto_reboot,
          :no_install => no_install,
          :no_remote => no_remote,
          :yes => yes,
          :allow_downgrade => allow_downgrade
        }
      end

    end
  end

  # arquivo 2
  module VagrantVbguest
    module Installers
      class Error < Vagrant::Errors::VagrantError
        error_namespace "vagrant_vbguest.errors.installer"
      end

      # This is the base class all installers must inherit from
      # It defines the basic structure of an Installer and should
      # never be used directly
      class Base
        include VagrantVbguest::Helpers::VmCompatible

        # Tests whether this installer class is applicable to the
        # current environment. Usually, testing for a specific OS.
        # Subclasses must override this method and return `true` if
        # they wish to handle.
        #
        # This method will be called only when an Installer detection
        # is run. It is ignored, when passing an Installer class
        # directly as an config (`installer`) option.
        #
        # @param vm [Vagrant::VM]
        # @return [Boolean]
        def self.match?(vm)
          false
        end

        # A helper method to cache the result of {Vagrant::Guest::Base#distro_dispatch}
        # which speeds up Installer detection runs a lot,
        # when having lots of Linux based Installer classes
        # to check.
        #
        # @see {Vagrant::Guest::Linux#distro_dispatch}
        # @return [Symbol] One of `:debian`, `:ubuntu`, `:gentoo`, `:fedora`, `:redhat`, `:suse`, `:arch`, `:windows`, `:amazon`
        def self.distro(vm)
          @@distro ||= {}
          @@distro[ vm_id(vm) ] ||= distro_name vm
        end

        attr_reader :env, :vm, :options, :host

        def initialize(vm, options=nil)
          @vm = vm
          @env = vm.env
          @options = options

          @host = VagrantVbguest::Hosts::VirtualBox.new(vm, options)
        end

        # The absolute file path of the GuestAdditions iso file should
        # be uploaded into the guest.
        # Subclasses must override this method!
        #
        # @return [String]
        def tmp_path
        end

        # The mountpoint path
        # Subclasses shall override this method, if they need to mount the uploaded file!
        #
        # @return [String]
        def mount_point
        end

        # Handles the installation process.
        # All necessary steps for an installation must be defined here.
        # This includes uploading the iso into the box, mounting,
        # installing and cleaning up.
        # The path to the local iso file should be obtained by calling +iso_file+
        # Subclasses must override this method!
        #
        # @param opts [Hash] Optional options Hash wich meight get passed to {Vagrant::Communication::SSH#execute} and firends
        # @yield [type, data] Takes a Block like {Vagrant::Communication::Base#execute} for realtime output of the command being executed
        # @yieldparam [String] type Type of the output, `:stdout`, `:stderr`, etc.
        # @yieldparam [String] data Data for the given output.
        def install(opts=nil, &block)
        end

        # Handels the rebuild of allready running GuestAdditions
        # It may happen, that the guest has the correct GuestAdditions
        # version running, but not the kernel module is not running.
        # This method should perform a rebuild or try to reload the
        # kernel module _without_ the GuestAdditions iso file.
        # If there is no way of rebuidling or reloading the
        # GuestAdditions on a specific system, this method should left
        # empty.
        # Subclasses should override this method.
        #
        # @param opts [Hash] Optional options Hash wich meight get passed to {Vagrant::Communication::SSH#execute} and firends
        # @yield [type, data] Takes a Block like {Vagrant::Communication::Base#execute} for realtime output of the command being executed
        # @yieldparam [String] type Type of the output, `:stdout`, `:stderr`, etc.
        # @yieldparam [String] data Data for the given output.
        def rebuild(opts=nil, &block)
        end

        # Restarts the allready installed GuestAdditions
        # It may happen, that the guest has the correct GuestAdditions
        # version installed, but for some reason are not (yet) runnig.
        # This method should execute the GuestAdditions system specific
        # init script in order to start it manually.
        # If there is no way of doing this on a specific system,
        # this method should left empty.
        # Subclasses should override this method.
        #
        # @param opts [Hash] Optional options Hash wich meight get passed to {Vagrant::Communication::SSH#execute} and firends
        # @yield [type, data] Takes a Block like {Vagrant::Communication::Base#execute} for realtime output of the command being executed
        # @yieldparam [String] type Type of the output, `:stdout`, `:stderr`, etc.
        # @yieldparam [String] data Data for the given output.
        def start(opts=nil, &block)
        end

        # Determinates if the GuestAdditions kernel module is loaded.
        # This method tests if there is a working GuestAdditions
        # kernel module. If there is none, {#rebuild} is being called.
        # If there is no way of telling if there is a working
        # GuestAddition for a specific system, this method should
        # return `true`.
        # Subclasses should override this method.
        #
        # @return [Boolean] `true` if the kernel module is loaded (and thus seems to work), `false` otherwise.
        def running?(opts=nil, &block)
          true
        end

        # This manipulate the run-list of a the vbguest machine.
        #
        # @return [Boolean]
        def reboot_after_install?
          false
        end

        # Does the guest installer provide tooling to manually start or rebuild guest additions?
        #
        # @return [Boolean]
        def provides_vboxadd_tools?
          false
        end

        # Is the tooling to manually start or rebuild guest additions installed on the guest?
        #
        # @return [Boolean]
        def vboxadd_tools_available?
          raise NotImplementedError
        end

        # Determinates the GuestAdditions version installed on the
        # guest system.
        #
        # @param reload [Boolean] Whether to read the value again or use
        #                  the cached value form an earlier call.
        # @return [Gem::Version] The version code of the VirtualBox Guest Additions
        #                  available on the guest, or `nil` if none installed.
        def guest_version(reload=false)
          return @guest_version if @guest_version && !reload

          @guest_version = VagrantVbguest::Version(@host.read_guest_additions_version)
        end

        # Determinates the host (eg VirtualBox) version
        # @param reload [Boolean] Whether to read the value again or use
        #                  the cached value form an earlier call.
        # @return [Gem::Version] The version code of the host provider
        def host_version(reload=false)
          return @host_version if @host_version && !reload

          @host_version = VagrantVbguest::Version(@host.version)
        end


        # Determinates the version of the GuestAdditions installer in use
        #
        # @return [Gem::Version] The version code of the GuestAdditions installer
        def installer_version(path_to_installer)
          version = nil
          communicate.sudo("#{path_to_installer} --info", :error_check => false) do |type, data|
            v = VagrantVbguest::Version(data, /\AIdentification.*\s(\d+\.\d+.\d+)/i)
            version = v if v
          end
          version
        end

        def installer_options
          options[:installer_options] || {}
        end

        # Helper to yield a warning message to the user, that the installation
        # will start _now_.
        # The message includes the host and installer version strings.
        def yield_installation_warning(path_to_installer)
          @env.ui.warn I18n.t("vagrant_vbguest.installing#{@options[:force] ? '_forced' : ''}",
            :guest_version     => (guest_version || I18n.t("vagrant_vbguest.unknown")),
            :installer_version => installer_version(path_to_installer) || I18n.t("vagrant_vbguest.unknown"))
        end

        # Helper to yield a warning message to the user, that the installation
        # will be rebuild using the installed GuestAdditions.
        # The message includes the host and installer version strings.
        def yield_rebuild_warning
          @env.ui.warn I18n.t("vagrant_vbguest.rebuild#{@options[:force] ? '_forced' : ''}",
            :guest_version => guest_version(true),
            :host_version => @host.version)
        end

        # Helper to yield a warning message to the user in the event that the
        # installer returned a non-zero exit status. Because lack of a window
        # system will cause this result in VirtualBox 4.2.8+, we don't want to
        # kill the entire boot process, but we do want to make sure the user
        # knows there could be a problem. The message includles the installer
        # version.
        def yield_installation_error_warning(path_to_installer)
          @env.ui.warn I18n.t("vagrant_vbguest.install_error",
            :installer_version => installer_version(path_to_installer) || I18n.t("vagrant_vbguest.unknown"))
        end
        # alias to old method name (containing a typo) for backwards compatibility
        alias_method :yield_installation_waring, :yield_installation_error_warning

        def iso_file
          @host.additions_file
        end
        alias_method :additions_file, :iso_file

        # A helper method to handle the GuestAdditions iso file upload
        # into the guest box.
        # The file will uploaded to the location given by the +temp_path+ method.
        #
        # @example Default upload
        #    upload(file)
        #
        # @param file [String] Path of the file to upload to the +tmp_path*
        def upload(file)
          env.ui.info(I18n.t("vagrant_vbguest.start_copy_iso", :from => file, :to => tmp_path))
          communicate.upload(file, tmp_path)
        end

        # A helper method to delete the uploaded GuestAdditions iso file
        # from the guest box
        def cleanup
          unless options[:no_cleanup]
            @host.cleanup
            communicate.execute("test -f #{tmp_path} && rm #{tmp_path}", :error_check => false) do |type, data|
              env.ui.error(data.chomp, :prefix => false)
            end
          end
        end
      end
    end
  end

  # arquivo 3
  module VagrantVbguest
    module Installers
      class CentOS < RedHat

        def self.match?(vm)
          super && communicate_to(vm).test('test -f /etc/centos-release')
        end

        # Install missing deps and yield up to regular linux installation
        def install(opts=nil, &block)
          install_kernel_deps(opts, &block)
          super
        end

        def installer_options
          @installer_options ||= {
            allow_kernel_upgrade: false,
            reboot_timeout: 300
          }.merge!(super)
        end

        protected

        def upgrade_kernel?
          raise 'TEST HERE. IT WILL BE FALSE ... ' + (installer_options[:allow_kernel_upgrade] ? 'TRUE!' : 'FALSE!')
        end

        def install_kernel_deps(opts=nil, &block)
          unless has_kernel_devel_info?
            update_release_repos(opts, &block)
            install_kernel_devel(opts, &block)
          end
        end

        def has_kernel_devel_info?
          unless instance_variable_defined?(:@has_kernel_devel_info)
            @has_kernel_devel_info = communicate.test('yum info kernel-devel-`uname -r`', sudo: true)
          end
          @has_kernel_devel_info
        end

        def has_rel_repo?
          unless instance_variable_defined?(:@has_rel_repo)
            rel = release_version
            @has_rel_repo = communicate.test(upgrade_kernel? ? 'yum repolist' : "yum repolist --enablerepo=C#{rel}-base --enablerepo=C#{rel}-updates")
          end
          @has_rel_repo
        end

        def release_version
          unless instance_variable_defined?(:@release_version)
            @release_version = nil
            version_pattern = /(\d+\.\d+(\.\d+)?)/
            communicate.sudo('cat /etc/centos-release') do |type, data|
              v = VagrantVbguest::Version(data, version_pattern)
              @release_version = v if v
            end
          end
          @release_version
        end

        def update_release_repos(opts=nil, &block)
          communicate.sudo('yum install -y centos-release', opts, &block)
        end

        def install_kernel_devel(opts=nil, &block)
          if upgrade_kernel?
            communicate.sudo('yum update -y kernel', opts, &block)
            communicate.sudo('yum install -y kernel-devel', opts, &block)
            communicate.sudo('shutdown -r now', opts, &block)

            begin
              sleep 10
            end until @vm.communicate.ready?
          else
            rel = has_rel_repo? ? release_version : '*'
            cmd = "yum install -y kernel-devel-`uname -r` --enablerepo=C#{rel}-base --enablerepo=C#{rel}-updates"
            communicate.sudo(cmd, opts, &block)
          end
        end

        def dependencies
          if has_kernel_devel_info?
            # keep the original redhat dependencies
            super
          else
            # we should have installed kernel-devel-`uname -r` via install_kernel_devel
            ['gcc', 'binutils', 'make', 'perl', 'bzip2', 'elfutils-libelf-devel'].join(' ')
          end
        end
      end
    end
  end

end

Vagrant.configure('2') do |config|
  config.vagrant.plugins = ['vagrant-vbguest']
  config.vm.box = 'centos/8'
  config.vbguest.installer_options = { allow_kernel_upgrade: true, reboot_timeout: 5000 }
end
```

**Comment by fnordfish** [comment]
Weird, I just ran it locally (build a gem and installed that one, just to be sure) and your Vagrantfile worked.
I'm going to simply merge your PR, put my stuff on top and release a beta version.

**Comment by fnordfish** [comment]
0.24.0.beta1 is now available

**Comment by pedrofurtado** [comment]
@fnordfish Tests is coming 👷  with the beta version 🤝

**Comment by pedrofurtado** [comment]
@fnordfish It works like a charm! 🎉 🍻 

Vagrantfiles for example:

CentOS 8: Done ✅ 
```ruby
Vagrant.configure('2') do |config|
  config.vagrant.plugins = {"vagrant-vbguest" => {"version" => "0.24.0.beta1"}}
  config.vm.box = 'centos/8'
  config.vm.synced_folder '.', '/vagrant', type: 'virtualbox'
  config.vbguest.installer_options = { allow_kernel_upgrade: true, reboot_timeout: 5000 }
end
```

CentOS 7: Done ✅ 
```ruby
Vagrant.configure('2') do |config|
  config.vagrant.plugins = {"vagrant-vbguest" => {"version" => "0.24.0.beta1"}}
  config.vm.box = 'centos/7'
  config.vm.synced_folder '.', '/vagrant', type: 'virtualbox'
  config.vbguest.installer_options = { allow_kernel_upgrade: true, reboot_timeout: 5000 }
end
```

**Comment by pedrofurtado** [comment]
@fnordfish Happy to see a oficial release of this great plugin, now working great with Centos 7 & 8 👍 🎖️

**Comment by konstruktoid** [comment]
Any instructions on how to test beta releases?

I still get `Stderr from the command: Error: Unknown repo: 'C*-base'` with the code below (full Vagrantfile at https://github.com/konstruktoid/ansible-role-hardening/blob/master/Vagrantfile), and it seems you can't install specific versions (e.g `vagrant plugin install vagrant-vbguest==0.24.0.beta1` or `vagrant plugin install vagrant-vbguest=0.24.0.beta1`).

```
  config.vm.define "centos" do |centos|
    centos.vagrant.plugins = {"vagrant-vbguest" => {"version" => "0.24.0.beta1"}}
    centos.vm.box = "centos/8"
    centos.ssh.insert_key = true
    centos.vm.network "private_network", ip: "10.2.3.43"
    centos.vm.provider "virtualbox" do |c|
      c.default_nic_type = "82543GC"
    end
    centos.vm.hostname = "centos"
    centos.vm.provision "shell",
      inline: "dnf install -y epel-release && dnf install -y ansible python3"
    centos.vm.provision "ansible" do |a|
      a.verbose = "v"
      a.limit = "all"
      a.playbook = "tests/test.yml"
      a.extra_vars = {
        "sshd_admin_net" => "0.0.0.0/0",
        "sshd_allow_groups" => "vagrant sudo",
        "ansible_python_interpreter" => "/usr/bin/python3"
      }
    end
  end
```

**Comment by konstruktoid** [comment]
```
$ git diff Vagrantfile 
diff --git a/Vagrantfile b/Vagrantfile
index 037abdc..57e1165 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -1,4 +1,5 @@
 Vagrant.configure("2") do |config|
+  config.vagrant.plugins = {"vagrant-vbguest" => {"version" => "0.24.0.beta1"}}
   config.vm.provider "virtualbox" do |v|
     v.default_nic_type = "Am79C973"
   end
```

```
$ vagrant up centos
Bringing machine 'centos' up with 'virtualbox' provider...
==> centos: Importing base box 'centos/8'...
[...]
Complete!
Error: Unknown repo: 'C*-base'
==> centos: Checking for guest additions in VM...
    centos: No guest additions were detected on the base box for this VM! Guest
    centos: additions are required for forwarded ports, shared folders, host only
    centos: networking, and more. If SSH fails on this machine, please install
    centos: the guest additions and repackage the box to continue.
    centos: 
    centos: This is not an error message; everything may continue to work properly,
    centos: in which case you may ignore this message.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` --enablerepo=C*-base --enablerepo=C*-updates

Stdout from the command:



Stderr from the command:

Error: Unknown repo: 'C*-base'
```

**Comment by fnordfish** [comment]
You will need the  `config.vbguest.installer_options = { allow_kernel_upgrade: true }` stuff

**Comment by konstruktoid** [comment]
Replacing with ~/.vagrant.d/gems/2.4.9/gems/vagrant-vbguest-0.23.0/lib/vagrant-vbguest/installers/centos.rb with https://raw.githubusercontent.com/pedrofurtado/vagrant-vbguest/1e4f6e36b20f6f8941d4df0556e9327232c0866d/lib/vagrant-vbguest/installers/centos.rb does work, but specifying the beta release as you've given example of above doesn't.

```
$ ls  ~/.vagrant.d/gems/2.4.9/gems/
micromachine-3.0.0  vagrant-scp-0.5.7  vagrant-vbguest-0.23.0  vagrant-vbguest-0.24.0.beta1
$ git diff Vagrantfile
diff --git a/Vagrantfile b/Vagrantfile
index 037abdc..8465be4 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -1,4 +1,6 @@
 Vagrant.configure("2") do |config|
+  config.vagrant.plugins = {"vagrant-vbguest" => {"version" => "0.24.0.beta1"}}
+  config.vbguest.installer_options = { allow_kernel_upgrade: true, reboot_timeout: 5000 }
   config.vm.provider "virtualbox" do |v|
     v.default_nic_type = "Am79C973"
   end
$ vagrant validate
There are errors in the configuration of this machine. Please fix
the following errors and try again:

VagrantVbguest::Config:
* The following settings shouldn't exist: installer_options
```

**Comment by fnordfish** [comment]
VagrantVbguest::Config:
  * The following settings shouldn't exist: installer_options

... suggest that the beta is not used, but the „old“ 0.23.0

**Comment by pedrofurtado** [comment]
@konstruktoid To avoid problems with cache of gems, remove the plugin vbguest globally from your machine and also locally removing the folder `.vagrant` in your machine.
I did this, and the version 0.24.0.beta1 works very well. 🤝 
Anyway, let us know if everything worked well 👍

**Comment by konstruktoid** [comment]
Exactly, so how do I enable the beta properly, and not by doing `wget -O ~/.vagrant.d/gems/2.4.9/gems/vagrant-vbguest-0.23.0/lib/vagrant-vbguest/installers/centos.rb  https://raw.githubusercontent.com/pedrofurtado/vagrant-vbguesta/1e4f6e36b20f6f8941d4df0556e9327232c0866d/lib/vagrant-vbguest/installers/centos.rb`?

**Comment by fnordfish** [comment]
Just to put it out there: `vagrant plugin install vagrant-vbguest --plugin-version=0.24.0.beta1`

**Comment by konstruktoid** [comment]
Thanks @fnordfish, that did it.
```
$ vagrant plugin install vagrant-vbguest --plugin-version=0.24.0.beta1
Installing the 'vagrant-vbguest --version '0.24.0.beta1'' plugin. This can take a few minutes...
Fetching: vagrant-vbguest-0.24.0.beta1.gem (100%)
Successfully uninstalled vagrant-vbguest-0.23.0
Installed the plugin 'vagrant-vbguest (0.24.0.beta1)'!
```

**Comment by fnordfish** [comment]
Seems to be working just fine for multiple people and centos versions. released as 0.24.0
Happy `vagrant plugin update vagrant-vbguest`

**Pull request merged**
