### PR TITLE
Added installer for Proxmox VE: Use different headers package name prefix

### PR DESCRIPTION
**Pull request by jstuyts**

### CODE REVIEW

**Comment by fnordfish** [comment]
Thanks for your work! Can you provide a public base-box I can use for testing?

**Comment by jstuyts** [comment]
Not at this moment, but I'll see what I can do in the next couple of days.

**Comment by jstuyts** [comment]
It took longer than I had hoped, but here it is: https://atlas.hashicorp.com/jstuyts/boxes/example-proxmoxve-tiny-amd64

**Comment by fnordfish** [comment]
Sorry, I will close this pull request. It's already hard enough to support the more common distributions.

You can however distribute your own gem as an extension to vbguest. Here is a sample which might help: https://github.com/dotless-de/vagrant-vbguest/tree/master/testdrive/vagrant-vbguest-unikorn

**Comment by jstuyts** [comment]
Okay, no problem. I might take a look at creating an extension myself.

**Pull request closed without merging**
