### PR TITLE
(GH-303) Add support for Amazon 2

### LINKED ISSUE #303: amazon2 does not work with shared folders
```
Bringing machine 'amazon2-agent' up with 'virtualbox' provider...
==> amazon2-agent: Importing base box 'winky/amazonlinux-2'...
==> amazon2-agent: Matching MAC address for NAT networking...
==> amazon2-agent: Checking if box 'winky/amazonlinux-2' is up to date...
==> amazon2-agent: Setting the name of the VM: sensu-puppet_amazon2-agent_1534963781658_75679
==> amazon2-agent: Fixed port collision for 22 => 2222. Now on port 2200.
==> amazon2-agent: Clearing any previously set network interfaces...
==> amazon2-agent: Preparing network interfaces based on configuration...
    amazon2-agent: Adapter 1: nat
    amazon2-agent: Adapter 2: hostonly
==> amazon2-agent: Forwarding ports...
    amazon2-agent: 22 (guest) => 2200 (host) (adapter 1)
==> amazon2-agent: Running 'pre-boot' VM customizations...
==> amazon2-agent: Booting VM...
==> amazon2-agent: Waiting for machine to boot. This may take a few minutes...
    amazon2-agent: SSH address: 127.0.0.1:2200
    amazon2-agent: SSH username: vagrant
    amazon2-agent: SSH auth method: private key
    amazon2-agent:
    amazon2-agent: Vagrant insecure key detected. Vagrant will automatically replace
    amazon2-agent: this with a newly generated keypair for better security.
    amazon2-agent:
    amazon2-agent: Inserting generated public key within guest...
    amazon2-agent: Removing insecure key from the guest if it's present...
    amazon2-agent: Key inserted! Disconnecting and reconnecting using new SSH key...
==> amazon2-agent: Machine booted and ready!
[amazon2-agent] GuestAdditions versions on your host (5.2.12) and guest (5.1.30) do not match.
The guest's platform ("amazon") is currently not supported, will try generic Linux method...
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.2.12 - guest version is 5.1.30
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.12 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 5.1.30 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: modprobe vboxsf failed
An error occurred during installation of VirtualBox Guest Additions 5.2.12. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> amazon2-agent: Checking for guest additions in VM...
    amazon2-agent: The guest additions on this VM do not match the installed version of
    amazon2-agent: VirtualBox! In most cases this is fine, but in rare cases it can
    amazon2-agent: prevent things such as shared folders from working properly. If you see
    amazon2-agent: shared folder errors, please make sure the guest additions within the
    amazon2-agent: virtual machine match the version of VirtualBox you have installed on
    amazon2-agent: your host and reload your VM.
    amazon2-agent:
    amazon2-agent: Guest Additions Version: 5.1.30
    amazon2-agent: VirtualBox Version: 5.2
==> amazon2-agent: Setting hostname...
==> amazon2-agent: Configuring and enabling network interfaces...
    amazon2-agent: SSH address: 127.0.0.1:2200
    amazon2-agent: SSH username: vagrant
    amazon2-agent: SSH auth method: private key
==> amazon2-agent: Mounting shared folders...
    amazon2-agent: /vagrant => /Users/gh/git/sensu-puppet
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

### PR DESCRIPTION
**Pull request by ghoneycutt**
Fixes #303

### CODE REVIEW

**Comment by ghoneycutt** [comment]
This PR allows amazon2 to work. I'm using this with sensu2 and puppet at https://github.com/sensu/sensu-puppet/tree/sensu2

**Comment by ghoneycutt** [comment]
@fnordfish could you please merge

**Comment by fnordfish** [comment]
Hi  

Sorry, I’m currently on tour.  
To understand your PR better, is every “Amazon2” Box a RedHat derivat?  
Is there a common box you can point me to?
I currently tend to create an own Instaaler class for new systems. In this special case it would inherit from RedHat and overwrite the matching logic.  

- send from my battery dying phone

**Comment by ghoneycutt** [comment]
Amazon linux is extremely similar to RedHat and other tools take a similar approach. I don't think it is worth having its own inherited class because there would be no other differences. You can use the Vagrant setup here - https://github.com/sensu/sensu-puppet/tree/sensu2

You'll see that EL6 and EL7 work and Amazon2 does not. After building a gem with the small change in this PR, Amazon2 works.

If you want me to change the code to the inheritance model or any other changes let me know. I'm very motivated to get this merged.

**Comment by fnordfish** [comment]
All right. Since this is a really small change, I'm just going to merge this.
However, if it turns out to require more work (eg. in future version of "amazon" boxes), I'd very much like it to get separated into an own class or even gem.

**Comment by ghoneycutt** [comment]
Thank you @fnordfish !!

**Comment by ghoneycutt** [comment]
What needs to be done to remove the beta from the the release? This makes it difficult to install as we must tell the project to install a specific version using the following command. This makes it very brittle for us.

`vagrant plugin install vagrant-vbguest --verbose --plugin-version 0.16.0.beta1`

**Comment by fnordfish** [comment]
It would be great if you could test the beta and double check that things are working. Ideally on multiple host machines/setups (think coworkers)  

If everything works out, I’m going to release 0.16 beginning next week.

**Comment by ghoneycutt** [comment]
I've tested with Amazon 2, EL6 and EL7.

**Pull request merged**
