### PR TITLE
Accept all messages in installer (#267)

### LINKED ISSUE #267: An error occurred during installation of VirtualBox Guest Additions 5.1.26 on ARTACK/debian-jessie
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ARTACK/debian-jessie' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
[default] GuestAdditions versions on your host (5.1.26) and guest (5.1.22) do not match.
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
linux-headers-3.16.0-4-amd64 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 139 not upgraded.
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.1.26 - guest version is 5.1.22
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.26 Guest Additions for Linux...........
VirtualBox Guest Additions installer
Removing installed version 5.1.22 of VirtualBox Guest Additions...
This system appears to have a version of the VirtualBox Guest Additions
already installed.  If it is part of the operating system and kept up-to-date,
there is most likely no need to replace it.  If it is not up-to-date, you
should get a notification when you start the system.  If you wish to replace
it with this version, please do not continue with this installation now, but
instead remove the current version first, following the instructions for the
operating system.

If your system simply has the remains of a version of the Additions you could
not remove you should probably continue now, and these will be removed during
installation.

Do you wish to continue? [yes or no]

Cancelling installation.
An error occurred during installation of VirtualBox Guest Additions 5.1.26. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Failed to start vboxadd.service: Unit vboxadd.service failed to load: No such file or directory.
Failed to start vboxadd-service.service: Unit vboxadd-service.service failed to load: No such file or directory.
==> default: Checking for guest additions in VM...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.4.11 project.dev
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
==> default: Mounting NFS shared folders...
==> default: Mounting shared folders...
    default: /vagrant => /path/to/project/shared_folder
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: unknown filesystem type 'vboxsf'
```

> Installing Virtualbox Guest Additions 5.1.26 - guest version is 5.1.22
> [...]
> Cancelling installation.
> An error occurred during installation of VirtualBox Guest Additions 5.1.26. Some functionality may not work as intended.

This error occured after upgrading Virtualbox on MacOS to `Version 5.1.26 r117224 (Qt5.6.2)` with virtualbox

## Versions

```
$ vboxmanage --version
5.1.26r117224
```

```
$ vagrant --version
Vagrant 1.9.7
```

```
$ vagrant plugin list
hostmanager (1.2.2)
  - Version Constraint: > 0
vagrant-hostmanager (1.8.7)
  - Version Constraint: > 0
vagrant-hostsupdater (1.0.2)
  - Version Constraint: > 0
vagrant-rekey-ssh (0.1.9)
  - Version Constraint: > 0
vagrant-share (1.1.9, system)
  - Version Constraint: > 0
vagrant-vbguest (0.14.2)
  - Version Constraint: > 0
```

```
$ vagrant box list -i
ARTACK/debian-jessie  (virtualbox, 8.1.0)
```

```
MacOS Sierra 10.12.6
```

Vagrant box debian version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.1 (jessie)
Release:	8.1
Codename:	jessie
```

```
$ uname -a
Linux project 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

## Workaround

```bash
$ vagrant destroy
$ vagrant up
```

This is not a very good workaround, but at least, installing from scratch does work.

### PR DESCRIPTION
**Pull request by jerr0328**
This should fix #267, which breaks when asking for user input. This works at least in the nominal condition.

### CODE REVIEW

**Comment by jerr0328** [comment]
I was able to test again the change, and it passes the prompt. I'm wondering if we should be concerned about the message though.

**Comment by dzschille** [comment]
Would be great if we can get the fix into master.
@fnordfish still on holiday? ;-)

**Comment by fnordfish** [comment]
Thanks for the bump. But I can already imagine the first bug-report asking to remove this. Can we , at least, make it configurable somehow? EG:
- `:yes => false` == `<install cmd>`
- `:yes => true` == `yes | <install cmd>`
- `:yes => "no"` == `yes "no" | <install cmd>`

**Comment by jerr0328** [comment]
I'll take a look at it tonight and hopefully have something in place for tomorrow.

**Comment by fnordfish** [comment]
😎 Thanks a lot!

**Comment by fnordfish** [comment]
released as v0.15.0

**Comment by dzschille** [comment]
I just tested the new release and it updated successfully the VBoxGuestAdditions to version 5.1.28. Before the VBoxGuestAdditions update failed because user input was expected.
Thanks a lot @jerr0328 for the improvement!

**Comment by pvalena** [comment]
It did not work for me, on `Win 7`. I had to fix it manually - https://github.com/dotless-de/vagrant-vbguest/issues/267#issuecomment-349726190.

**Pull request merged**
