### PR TITLE
Added windows installer to update guest additions on windows guest runni...

### PR DESCRIPTION
**Pull request by fabriciocolombo**
...ng on windows host.

### CODE REVIEW

**Comment by msabramo** [comment]
Wow, does this allow updating the additions on a Windows guest? Would love that since right now I'm getting:

```
Sorry, don't know how to check guest version of Virtualbox Guest Additions on this platform. Stopping installation.
```

**Comment by dpryden** [comment]
Hey, I stumbled across this as well. Do I understand correctly that this will resolve issue #65? If so, what would it take to get this merged? The merge conflicts look pretty minimal to me.

**Comment by fnordfish** [comment]
Thanks for your work, but I'm currently not able to add support for more providers (as all the hassle with linux differences are bad enough). However, I've merged the part where you moved the `distro` method to `Installers::Base`.

**Comment by dpryden** [comment]
@fnordfish: If your intention is not to support Windows guests at all, I for one would appreciate it if that were called out explicitly and prominently in the documentation. It's also very unfortunate, as my primary use case is with Windows guests on a Linux host, and thus this project is not very useful to me in its current form.

**Comment by dpryden** [comment]
@fnordfish: Also, your comment here seems to be at odds with your comment on issue #65. Perhaps #65 should be closed as well, to prevent others in the future from misunderstanding and thinking pull requests of this sort would be welcome?

**Comment by fnordfish** [comment]
@dpryden: I'm sorry to disappoint you, but I'm simply not able to pull together the time to support such a big target as "windows". The same goes for things like macOS or any other non-open OS for that matter. 

Vbguest advertises the use of custom installers in the readme's "Advanced Usage" section. If you need to support multiple projects, you might find this sample of [creating a vagrant-vbguest extension plugin](https://github.com/dotless-de/vagrant-vbguest/tree/master/testdrive/vagrant-vbguest-unikorn) useful.

The comments you refer to are 3 year old. I tend to leave issue open so people can discuss their solutions in them.
But you are right, I should try to find a way which kind of pull requests I'm willing to merge.

**Pull request closed without merging**
